# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='markdown',
            field=models.BooleanField(default=False),
        ),
    ]
